name: "Deploy: .NET 6 Service"

env:
  TARGET_BASE_PATH: "c$/dev"
  SERVICE_DIR: "${{ github.event.repository.name }}"
  JOB_NAME: "${{ github.event.repository.name }}"

on: 
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: string  
      build_workflow:
        description: 'Build workflow absolute path'
        required: false
        type: string
      target:
        description: 'Specific target server (domain name or address)'
        required: true
        type: string

jobs:
  build:
    # This job will only run if 'build_before' is checked
    if: ${{ inputs.build_workflow != '' }}
    uses: ${{ inputs.build_workflow }}
    
  deploy:
    runs-on: [self-hosted, windows, x64]
    needs: build
    if: ${{ always() && needs.build.result != 'failure' }}
    env:
      target: ${{ inputs.target }}
    steps:  
      - name: "Deploying to ${{ env.target }} as ${{ inputs.environment }}"
        run: echo "run ${{ github.run_number }} ..." 
     
      - name: "Copy 'Release' folder"
        run: |
          $sourcePath = "${{ env.SERVICE_DIR }}/bin/Release/net6.0"
          $targetPath = "\\${{ env.target }}\${{ env.TARGET_BASE_PATH }}\${{ env.JOB_NAME }}\r${{ github.run_number }}\"
          echo "Deploying to $targetPath"
          if (!(Test-Path -Path $targetPath)) {
            New-Item -ItemType Directory -Force -Path $targetPath
          }     
          Copy-Item -Path "$sourcePath\*" -Destination "$targetPath" -Recurse
          
      
    
